#ifndef __EVENT_MANAGEMENT_H__
#define __EVENT_MANAGEMENT_H__

#include <stdint.h>

/* this subproject creates a linked-list based event logging system
 * logging the timestamp generated by the STM32G4 RTC
 *
 */

#define MAX_EVENT_DESC_LEN   32

typedef struct EventNode
{
    uint32_t timestamp;   //timestamp from the RTC
    char description[MAX_EVENT_DESC_LEN];  //event description
    struct EventNode *next;   //pointer to the next node
} EventNode_t;

void AddEvent(const char *description);
void PrintEventList(void);
void RemoveEventByTimestamp(uint32_t timestamp);
void HandleUartCommand(const char *command);

#endif //EVENT_MANAGEMENT_H